name: Python CI #Name of the workflow

#Trigger the workflow on any push to the main branch or pull request.
on: #keyword to start an event
    push: #this is the event, and there could be any nummber of events  such as push, pull, merge, delete.
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            #step-1 Check out the code from the repository 
            - name: Check out code -1
              uses: action/checkout@v2

            #step-2 Set up python environment
            - name: Set up python-2
              uses: actions/setup-pyton@v2
              with:
                python-version: '3.8'

            #Step-3 Install Dependencies
            - name: Install dependencies -2
              run:
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            #step-4 Run test
            - name: Run tests
              run: pytest
          
